#!/usr/bin/env node

/**
 * Auto-generate beforeAfterData.js by scanning the beforeafter folder
 * Run: node scripts/generateBeforeAfterPairs.mjs
 * Or: npm run generate-beforeafter
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const beforeAfterFolder = path.join(__dirname, '../public/images/beforeafter')
const outputFile = path.join(__dirname, '../src/data/beforeAfterData.js')

// Ensure folder exists
if (!fs.existsSync(beforeAfterFolder)) {
  console.log('📁 Creating beforeafter folder...')
  fs.mkdirSync(beforeAfterFolder, { recursive: true })
  console.log('✅ Folder created. Add your images (name-1.ext and name-2.ext)')
  process.exit(0)
}

// Read all files in folder
const files = fs.readdirSync(beforeAfterFolder).filter(file => {
  const ext = path.extname(file).toLowerCase()
  return ['.jpg', '.jpeg', '.png', '.webp'].includes(ext)
})

if (files.length === 0) {
  console.log('⚠️  No images found in beforeafter folder')
  console.log(`   Folder: ${beforeAfterFolder}`)
  process.exit(0)
}

// Group files by base name (everything before -1 or -2)
const pairsMap = new Map()

files.forEach(file => {
  const match = file.match(/^(.+)-([12])\.(jpg|jpeg|png|webp)$/i)
  if (match) {
    const [, baseName, number, ext] = match
    const key = baseName.toLowerCase()
    
    if (!pairsMap.has(key)) {
      pairsMap.set(key, { name: baseName, before: null, after: null })
    }
    
    const pair = pairsMap.get(key)
    const filename = `${baseName}-${number}.${ext.toLowerCase()}`
    
    if (number === '1') {
      pair.before = filename
    } else if (number === '2') {
      pair.after = filename
    }
  }
})

// Filter to only complete pairs
const completePairs = Array.from(pairsMap.values())
  .filter(pair => pair.before && pair.after)
  .sort((a, b) => a.name.localeCompare(b.name))

if (completePairs.length === 0) {
  console.log('⚠️  No complete pairs found.')
  console.log('   Make sure files follow pattern: name-1.ext and name-2.ext')
  console.log(`   Found files: ${files.join(', ')}`)
  process.exit(1)
}

// Generate the data file
const fileContent = `// Auto-generated by scripts/generateBeforeAfterPairs.mjs
// Run 'npm run generate-beforeafter' to regenerate
// Images are automatically detected from /public/images/beforeafter/

export const beforeAfterPairs = [
${completePairs.map(pair => `  { name: '${pair.name}', before: '${pair.before}', after: '${pair.after}' },`).join('\n')}
]

// Helper to get image path
export const getBeforeAfterImagePath = (filename) => \`/images/beforeafter/\${filename}\`
`

fs.writeFileSync(outputFile, fileContent, 'utf8')

console.log(`✅ Generated ${completePairs.length} image pair(s):`)
completePairs.forEach(pair => {
  console.log(`   - ${pair.name}: ${pair.before} ↔ ${pair.after}`)
})
console.log(`\n📝 Updated: ${outputFile}`)
